name: CI — build & test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Publish API & Web projects (self-contained artifacts)
        run: |
          dotnet publish CoinDispenser.Api -c Release -o ./out/api
          dotnet publish CoinDispenser.Web -c Release -o ./out/web

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coin-dispenser-artifacts
          path: out
